### ISSUE TITLE
Automatic updates - provide product ID

### ISSUE THREAD

**Issue by EtienneBruines** [keygen-sh/keygen-go#7]
While debugging the `keygen.Upgrade` command that always seems to return `ErrUpgradeNotAvailable` (HTTP 404), I noticed that the `Upgrade` command does not provide the Keygen-Server with any product ID in the query. 

How do I provide that, to avoid future collisions with version numbers?   (It's quite common for versions to overlap, e.g. multiple products having version `1.0.0` and `1.0.1`)

**Comment by ezekg** [comment]
Authentication is typically handled using a license key or token and both of these are automatically scoped to the license's product. However, I do think there should be a product option to avoid collisions with releases that have an `OPEN` distribution strategy (since those can cross the aforementioned boundary).

**Comment by ezekg** [comment]
Implemented in v2.4.0.
